/**
 * 1. Force the filtered total into the Gateway available data
 */
add_filter('woocommerce_available_payment_gateways', 'spb_force_gateway_total_sync');
function spb_force_gateway_total_sync($available_gateways) {
    if (is_admin()) return $available_gateways;

    $order_id = absint(get_query_var('order-pay'));
    if (!$order_id) return $available_gateways;

    $order = wc_get_order($order_id);
    if ($order && $order->get_meta('spb_payment_link_sent') === '1') {
        $partial_amount = $order->get_meta('spb_partial_payment_requested');
        
        // This is a "surgical" strike to force the gateway's internal order reference
        if (!empty($partial_amount)) {
            $order->set_total($partial_amount); 
            // We don't save the order here to keep the backend 27500 correct
        }
    }
    return $available_gateways;
}

/**
 * 2. Specifically target the Vinti4 redirect data if it uses standard WC Order
 */
add_filter('woocommerce_order_get_total', 'spb_vinti4_modal_final_force', 20, 2);
function spb_vinti4_modal_final_force($total, $order) {
    if (is_admin()) return $total;

    $link_sent = $order->get_meta('spb_payment_link_sent');
    $partial_amount = $order->get_meta('spb_partial_payment_requested');

    if ($link_sent === '1' && !empty($partial_amount)) {
        // We use a high priority (20) to make sure we are the last ones touching the total
        return (float) $partial_amount;
    }
    return $total;
}

/**
 * 3. GLOBAL FORCE OVERRIDE
 * This intercepts the order object early in the page load.
 * It ensures the 'Fingerprint' generated by Vinti4 uses the deposit amount.
 */
add_action('wp', 'spb_global_order_total_force');
function spb_global_order_total_force() {
    // Only run on the checkout/pay-order page
    if (is_admin() || !is_wc_endpoint_url('order-pay')) return;

    $order_id = absint(get_query_var('order-pay'));
    if (!$order_id) return;

    $order = wc_get_order($order_id);
    if ($order && $order->get_meta('spb_payment_link_sent') === '1') {
        $partial_amount = $order->get_meta('spb_partial_payment_requested');
        
        if (!empty($partial_amount)) {
            // This forces the value into the object's core property in RAM.
            // When the Vinti4 plugin calls $order->get_total(), it will get the deposit.
            $order->set_total((float)$partial_amount);
        }
    }
}